[project]
name = "vocabulatu-trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pip>=25.1.1",
    "polars>=1.29.0",
    "rich>=14.0.0",
]
